-- =============================================
-- LAO LOTTO - LINE Bot Database Schema
-- Migration: 125_add_line_bot_schema.sql
-- =============================================

-- 1. Add line_user_id to profiles table (for linking user account to LINE)
ALTER TABLE profiles
ADD COLUMN IF NOT EXISTS line_user_id TEXT UNIQUE;

-- 2. Create line_groups table
CREATE TABLE IF NOT EXISTS line_groups (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    line_group_id TEXT UNIQUE NOT NULL, -- The LINE group chat ID (starts with C...)
    dealer_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE, -- Bound dealer
    lottery_type TEXT DEFAULT 'lao', -- Default lottery type for this group (e.g. thai, lao, hanoi)
    group_name TEXT, -- Optional LINE group name
    binding_code TEXT UNIQUE, -- Code generated by web for binding group (e.g., BG-123456)
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

-- 3. Create indexes for performance
CREATE INDEX IF NOT EXISTS idx_line_groups_line_group_id ON line_groups(line_group_id);
CREATE INDEX IF NOT EXISTS idx_line_groups_dealer_id ON line_groups(dealer_id);
CREATE INDEX IF NOT EXISTS idx_line_groups_binding_code ON line_groups(binding_code);

-- 4. Enable Row Level Security (RLS)
ALTER TABLE line_groups ENABLE ROW LEVEL SECURITY;

-- 5. Drop existing policies if any
DROP POLICY IF EXISTS "Dealers and Superadmins can manage line groups" ON line_groups;
DROP POLICY IF EXISTS "Service role can select line groups" ON line_groups;

-- 6. Create policies
-- Dealers can perform ALL operations on their own groups, Superadmins can manage all
CREATE POLICY "Dealers and Superadmins can manage line groups" ON line_groups
    FOR ALL USING (
        auth.uid() = dealer_id
        OR EXISTS (
            SELECT 1 FROM profiles 
            WHERE id = auth.uid() AND role = 'superadmin'
        )
    );

-- 7. Trigger to update updated_at
CREATE OR REPLACE FUNCTION update_line_groups_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_update_line_groups_updated_at ON line_groups;
CREATE TRIGGER trg_update_line_groups_updated_at
    BEFORE UPDATE ON line_groups
    FOR EACH ROW
    EXECUTE FUNCTION update_line_groups_updated_at();
